ignore:
  - "path/to/folder"  # ignore folders and all its contents
  - "src/*/*/backends/backend_config.py" # ignore the backend_config.py file for all plugins
  - "**/__init__.py"
  
  
coverage:
  status:
    patch:
      default:
        target: 0%
    project:
      default:
        target: 80%
